import Head from "next/head";

const Header = ({ children }) => {
  return (
    <>
      <Head>
        <title>NRNA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Header;
